### ISSUE TITLE
demoのnpm run swiftbuildがうまくいかない

### ISSUE THREAD

**Issue by omochi** [omochi/CodableToTypeScript#87]
```
[omochi@omochi-iMacPro demo (main =)]$ swift --version
SwiftWasm Swift version 5.7.2 (swiftlang-5.7.1)
Target: x86_64-apple-darwin21.6.0
[omochi@omochi-iMacPro demo (main =)]$ npm run swiftbuild

> c2tsdemo@0.0.0 swiftbuild
> swift build --product C2TS --triple wasm32-unknown-wasi -c release && wasm-opt -Os .build/release/C2TS.wasm -o public/C2TS.wasm && wasm-strip public/C2TS.wasm

warning: 'wasmcallablekit': 'wasmcallablekit' dependency on 'https://github.com/omochi/CodableToTypeScript' conflicts with dependency on 'https://github.com/sidepelican/CodableToTypeScript.git' which has the same identity 'codabletotypescript'. this will be escalated to an error in future versions of SwiftPM.
Building for production...
[16/16] Linking C2TS.wasm
Build complete! (356.86s)
node:internal/child_process:413
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -8
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:743:9)
    at Object.<anonymous> (/Users/omochi/github/omochi/CodableToTypeScript/demo/node_modules/wasm-opt/bin/wasm-opt.js:10:20)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -8,
  code: 'Unknown system error -8',
  syscall: 'spawn'
}

Node.js v18.11.0
```

だが、その場で `wasm-opt` 以降のステップを個別に手打ちした場合はうまくいった

```
[omochi@omochi-iMacPro demo (main =)]$ which wasm-opt
/usr/local/bin/wasm-opt
[omochi@omochi-iMacPro demo (main =)]$ wasm-opt -Os .build/release/C2TS.wasm -o public/C2TS.wasm 
[omochi@omochi-iMacPro demo (main =)]$ wasm-strip public/C2TS.wasm 
```

**Comment by omochi** [comment]
@sidepelican なにかわかりますか？

**Comment by sidepelican** [comment]
むむ、不思議ですね。
参考程度に、僕が使ってるnodeは `v18.12.1` で、wasm-optはPATHに存在しません。

**Comment by omochi** [comment]
こういうことか。

```
$ brew unlink binaryen
$ which wasm-opt
$ npx wasm-opt
node:internal/child_process:413
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -8
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:743:9)
    at Object.<anonymous> (/Users/omochi/github/omochi/CodableToTypeScript/demo/node_modules/wasm-opt/bin/wasm-opt.js:10:20)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -8,
  code: 'Unknown system error -8',
  syscall: 'spawn'
}

Node.js v18.11.0
```

`npx wasm-opt` 単体で問題が再現しました。

**Comment by omochi** [comment]
```
$ npm uninstall wasm-opt
$ npm install wasm-opt
```

で直った。

**Comment by sidepelican** [comment]
手元でnodeを18.11.0にして、`npm run swiftbuild`や`npx wasm-opt`しても動きました。不思議ですね

**Comment by omochi** [comment]
PATHに wasm-opt が居る状態で npm install する順番だと何か名前解決の挙動が変わってしまうのかも・・・？

**Comment by omochi** [comment]
解決
